version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "policyglass-demo-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1clyu9bxor9yb"
s3_prefix = "policyglass-demo-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
