AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  policyglass-demo-api

  Demo API for policyglass.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  PolicyGlassShatterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: policyglass_shatter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        PolicyGlassShatter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /shatter
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PolicyGlassShatterApi:
    Description: "API Gateway endpoint URL for Prod stage for PolicyGlass shatter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shatter/"
  PolicyGlassShatterFunction:
    Description: "PolicyGlass Shatter Lambda Function ARN"
    Value: !GetAtt PolicyGlassShatterFunction.Arn
  PolicyGlassShatterFunctionIamRole:
    Description: "Implicit IAM Role created for PolicyGlass shatter function"
    Value: !GetAtt PolicyGlassShatterFunctionRole.Arn
